using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Misp.Kernel.Application
{
    public class FunctionalitiesCode
    {

        public static string HOME_PAGE_FUNCTIONALITY    = "HOME_PAGE";

        public static string LOGOUT_FUNCTIONALITY       = "LOGOUT";

        public static string FILE_FUNCTIONALITY         = "FILE_FONCTIONALITY";

        public static string FILE_SAVE_FUNCTIONALITY = "FILE_SAVE_FONCTIONALITY";

        public static string FILE_SAVE_AS_FUNCTIONALITY = "FILE_SAVE_AS_FONCTIONALITY";

        public static string ABOUT_FUNCTIONALITY        = "ABOUT_FUNCTIONALITY";

        public static string CLEAR_ALL_ALLOCATION_FUNCTIONALITY = "CLEAR_ALL_ALLOCATION_FUNCTIONALITY";
        public static string RUN_ALL_ALLOCATION_FUNCTIONALITY = "RUN_ALL_ALLOCATION_FUNCTIONALITY";
        
        public static string NEW_AUTOMATIC_SOURCING_FUNCTIONALITY = "NEW_AUTOMATIC_SOURCING_FUNCTIONALITY";



        public static string ALLOCATION_LOG_FUNCTIONALITY = "ALLOCATION_LOG_FUNCTIONALITY";

        public static string EXPORT_BUDGET = "EXPORT_BUDGET";

        public static string UPLOAD_MULTIPLE_FILES = "UPLOAD_MULTIPLE_FILES";
        public static string PROPERTIES_FUNCTIONALITY = "PROPERTIES_FUNCTIONALITY";
        public static string NEW_GROUP_FUNCTIONALITY = "NEW_GROUP_FUNCTIONALITY";
        public static string LIST_GROUP_FUNCTIONALITY = "LIST_GROUP_FUNCTIONALITY";

        public static string LOAD_TRANSFORMATION_TREES_FUNCTIONALITY = "LOAD_TRANSFORMATION_TREES_FUNCTIONALITY";
        public static string CLEAR_TRANSFORMATION_TREES_FUNCTIONALITY = "CLEAR_TRANSFORMATION_TREES_FUNCTIONALITY";

        public static string NEW_COMBINED_TRANSFORMATION_TREES_FUNCTIONALITY = "NEW_COMBINED_TRANSFORMATION_TREES_FUNCTIONALITY";
        public static string LIST_COMBINED_TRANSFORMATION_TREES_FUNCTIONALITY = "LIST_COMBINED_TRANSFORMATION_TREES_FUNCTIONALITY";

        public static string BACKUP_FUNCTIONALITY = "BACKUP_FUNCTIONALITY";
        public static string BACKUP_SIMPLE_FUNCTIONALITY = "BACKUP_SIMPLE_FUNCTIONALITY";
        public static string BACKUP_AUTOMATIC_FUNCTIONALITY = "BACKUP_AUTOMATIC_FUNCTIONALITY";


        //INITIATION
        public static string INITIATION_FUNCTIONALITY = "INITIATION_FUNCTIONALITY";
        public static string MODEL_FUNCTIONALITY = "MODEL_FUNCTIONALITY";
        public static string PERIOD_FUNCTIONALITY = "PERIOD_FUNCTIONALITY";
        public static string MEASURE_FUNCTIONALITY = "MEASURE_FUNCTIONALITY";


        //SOURCING
        public static string NEW_INPUT_TABLE_FUNCTIONALITY = "NEW_INPUT_TABLE_FUNCTIONALITY";
        public static string LIST_INPUT_TABLE_FUNCTIONALITY = "LIST_INPUT_TABLE_FUNCTIONALITY";

        public static string NEW_TARGET_FUNCTIONALITY = "NEW_TARGET_FUNCTIONALITY";
        public static string NEW_AUTOMATIC_TARGET_FUNCTIONALITY = "NEW_AUTOMATIC_TARGET_FUNCTIONALITY";
        public static string LIST_AUTOMATIC_TARGET = "LIST_AUTOMATIC_TARGET";
        public static string LIST_TARGET_FUNCTIONALITY = "LIST_TARGET_FUNCTIONALITY";

        public static string NEW_DESIGN_FUNCTIONALITY = "NEW_DESIGN_FUNCTIONALITY";
        public static string LIST_DESIGN_FUNCTIONALITY = "LIST_DESIGN_FUNCTIONALITY";
        
        public static string UPLOAD_STRUCTURED_FILE_FUNCTIONALITY = "UPLOAD_STRUCTURED_FILE_FUNCTIONALITY";
        public static string LIST_AUTOMATIC_SOURCING = "LIST_AUTOMATIC_SOURCING";


        //REPORTING
        public static string NEW_REPORT_FUNCTIONALITY = "NEW_REPORT_FUNCTIONALITY";
        public static string LIST_REPORT_FUNCTIONALITY = "LIST_REPORT_FUNCTIONALITY";

        public static string NEW_STRUCTURED_REPORT_FUNCTIONALITY = "NEW_STRUCTURED_REPORT_FUNCTIONALITY";
        public static string LIST_STRUCTURED_REPORT_FUNCTIONALITY = "LIST_STRUCTURED_REPORT_FUNCTIONALITY";

        public static string NEW_CALCULATED_MEASURE_FUNCTIONALITY = "NEW_CALCULATED_MEASURE_FUNCTIONALITY";
        public static string LIST_CALCULATED_MEASURE_FUNCTIONALITY = "LIST_CALCULATED_MEASURE_FUNCTIONALITY";

        //PLANIFICATION
        public static string NEW_TRANSFORMATION_TREE_FUNCTIONALITY = "NEW_TRANSFORMATION_TREE_FUNCTIONALITY";
        public static string LIST_TRANSFORMATION_TREE_FUNCTIONALITY = "LIST_TRANSFORMATION_TREE_FUNCTIONALITY";
        public static string NEW_TRANSFORMATION_TABLE_FUNCTIONALITY = "NEW_TRANSFORMATION_TABLE_FUNCTIONALITY";
        public static string NEW_SLIDE_FUNCTIONALITY = "NEW_SLIDE_FUNCTIONALITY";

        //GRID
        public static string GRID_FUNCTIONALITY = "GRID_FUNCTIONALITY";
        public static string NEW_AUTOMATIC_GRID_FUNCTIONALITY = "NEW_AUTOMATIC_GRID_FUNCTIONALITY";
        public static string LIST_AUTOMATIC_GRID_FUNCTIONALITY = "LIST_AUTOMATIC_GRID_FUNCTIONALITY";
		
		public static string NEW_INPUT_GRID_FUNCTIONALITY = "NEW_INPUT_GRID_FUNCTIONALITY";
        public static string LIST_INPUT_GRID_FUNCTIONALITY = "LIST_INPUT_GRID_FUNCTIONALITY";

        public static string NEW_REPORT_GRID_FUNCTIONALITY = "NEW_REPORT_GRID_FUNCTIONALITY";
        public static string LIST_REPORT_GRID_FUNCTIONALITY = "LIST_REPORT_GRID_FUNCTIONALITY";


        //PIVOT_TABLE
        public static string NEW_PIVOT_TABLE_FUNCTIONALITY = "NEW_PIVOT_TABLE_FUNCTIONALITY";
        public static string LIST_PIVOT_TABLE_FUNCTIONALITY = "LIST_PIVOT_TABLE_FUNCTIONALITY";

        

        //RECONCILIATION
        public static string RECONCILIATION_FILTERS_FUNCTIONALITY = "RECONCILIATION_FILTERS_FUNCTIONALITY";
        public static string LIST_RECONCILIATION_FILTERS_FUNCTIONALITY = "LIST_RECONCILIATION_FILTERS_FUNCTIONALITY";
        public static string RECONCILIATION_POSTING_FUNCTIONALITY = "RECONCILIATION_POSTING_FUNCTIONALITY";
        public static string TRANSACTION_FILE_TYPES_FUNCTIONALITY = "TRANSACTION_FILE_TYPES_FUNCTIONALITY";
        public static string RECONCILIATION_RUN_CONFIRM = "RECONCILIATION_RUN_CONFIRM";
        public static string RECONCILIATION_CONTEXT_FUNCTIONALITY = "RECONCILIATION_CONTEXT_FUNCTIONALITY";
        
        public static string NEW_POSTING_GRID_FUNCTIONALITY = "NEW_POSTING_GRID_FUNCTIONALITY";
        public static string LIST_POSTING_GRID_FUNCTIONALITY = "LIST_POSTING_GRID_FUNCTIONALITY";
        public static string NEW_AUTOMATIC_POSTING_GRID_FUNCTIONALITY = "NEW_AUTOMATIC_POSTING_GRID_FUNCTIONALITY";
        public static string LIST_AUTOMATIC_POSTING_GRID_FUNCTIONALITY = "LIST_AUTOMATIC_POSTING_GRID_FUNCTIONALITY";

        //ADMINISTRATION
        public static string ADMINISTRATION_NEW_USER = "ADMINISTRATION_NEW_USER";
        public static string ADMINISTRATION_LIST_USER = "ADMINISTRATION_LIST_USER";
        public static string ADMINISTRATION_LIST_PROFIL = "ADMINISTRATION_LIST_PROFIL";
        public static string ADMINISTRATION_NEW_PROFIL = "ADMINISTRATION_NEW_PROFIL";
        public static string ADMINISTRATION_ROLE = "ADMINISTRATION_ROLE";
        public static string ADMINISTRATION_LIST_ROLE = "ADMINISTRATION_LIST_ROLE";
        public static string ADMINISTRATION_CONNECTED_USER_PROFILE = "ADMINISTRATION_CONNECTED_USER_PROFILE";
    }
}
